name: formatio

services:
  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: default_user
      RABBITMQ_DEFAULT_PASS: default_pass
      RABBITMQ_DEFAULT_VHOST: default_vhost
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis_volume:/root/redis

volumes:
  postgres_volume:
  rabbitmq_volume:
  redis_volume:
